In [9]:
# import manipulation lybraries
import pandas as pd
import numpy as np 
# import visualization lybraries
import seaborn as sns
import matplotlib.pyplot as plt

#import machine learning lybraries
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler,OneHotEncoder
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
import pandas as pd
from sklearn.compose import ColumnTransformer

In [10]:
#=============================================
#            data ingestion
#=============================================
def data_ingestion():
    df = pd.read_csv(r'C:\Mental_Health_Prediction_Model\data\raw\survey_dataset.csv')
    return df

In [11]:
df = data_ingestion()

In [12]:
df.columns

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [13]:
data = df.copy()
data.drop(columns=['Country','state','Timestamp','comments'], axis=1, inplace=True)

In [14]:
# check null values
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [15]:
# check duplicate
df.duplicated().sum()

np.int64(0)

In [16]:
df["self_employed"].fillna(df["self_employed"].mode()[0], inplace=True)


C:\Users\kante\AppData\Local\Temp\ipykernel_31184\30466794.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["self_employed"].fillna(df["self_employed"].mode()[0], inplace=True)


In [17]:
df['work_interfere'].fillna('N\A',inplace= True)

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\kante\AppData\Local\Temp\ipykernel_31184\3298628936.py:1: SyntaxWarning: invalid escape sequence '\A'
  df['work_interfere'].fillna('N\A',inplace= True)
C:\Users\kante\AppData\Local\Temp\ipykernel_31184\3298628936.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['work_interfere'].fillna('N\A',inplace= True)


In [18]:
from collections import OrderedDict

#=============================================
#            data_exploration
#=============================================
def data_exploration(df):

    numerical_col = df.select_dtypes(exclude='object').columns
    categorical_col = df.select_dtypes(include='object').columns

    # Initialize lists to store dictionaries of statistics
    numerical_stats = []
    categorical_stats = []

    # ---------- Numerical Analysis ----------
    Q1 = df[numerical_col].quantile(0.25)
    Q3 = df[numerical_col].quantile(0.75)
    IQR = Q3 - Q1
    LW = Q1 - 1.5 * IQR
    UW = Q3 + 1.5 * IQR
    outlier_count = ((df[numerical_col] < LW) | (df[numerical_col] > UW))

    for col in numerical_col:
        # Create an OrderedDict for the current column's stats
        num_stats = OrderedDict({
            "feature": col,
            "mean": df[col].mean(),
            "median": df[col].median(),
            "quartile_1": Q1[col],
            "quartile_3": Q3[col],
            "IQR": IQR[col],
            "lower_whisker": LW[col],
            "upper_whisker": UW[col],
            "outlier_count": outlier_count[col].sum(),
            "std_dev": df[col].std(),
            "variance": df[col].var(),
            "skewness": df[col].skew(),
            "kurtosis": df[col].kurtosis()
        })
        # Append this dictionary to the list
        numerical_stats.append(num_stats)

    # ---------- Categorical Analysis ----------
    for col in categorical_col:
        # Create an OrderedDict for the current column's stats
        cat_stats = OrderedDict({
            "feature": col,
            "unique_values": df[col].nunique(),
            "mode": df[col].mode()[0] if not df[col].mode().empty else None,
            "missing_values": df[col].isnull().sum()
        })
        # Append this dictionary to the list
        categorical_stats.append(cat_stats)

    # return both reports
    numerical_report = pd.DataFrame(numerical_stats)
    categorical_report = pd.DataFrame(categorical_stats)

    return numerical_report, categorical_report

In [23]:
#=============================================
#            Model Build
#=============================================

def model_building(df,numerical_col,categorical_col):

    # TARGET
    X = df.drop("treatment", axis=1)
    y = df["treatment"]

    # Encode Target
    le = LabelEncoder()
    y = le.fit_transform(y)

    # SPLIT
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )


    # PREPROCESSOR
    preprocessor = ColumnTransformer([
        ("numerical", MinMaxScaler().numerical_col),
        ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical_col)
    ])

    # MODELS
    models = {
        "RandomForest": RandomForestClassifier(random_state=42),
        "GradientBoosting": GradientBoostingClassifier(random_state=42),
        "XGBoost": XGBClassifier(random_state=42)
    }

    trained_pipelines = {}
    scores = {}

    # TRAIN EACH MODEL
    for name, model in models.items():

        pipeline = Pipeline(steps=[
            ("preprocessing", preprocessor),
            ("smote", SMOTE(random_state=42)),
            ("classifier", model)
        ])

        pipeline.fit(X_train, y_train)
        y_pred = pipeline.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)

        trained_pipelines[name] = pipeline
        scores[name] = accuracy

        print(confusion_matrix(y_test, y_pred))
        print(f"{name} Results")
        print(f"\n{name} Accuracy: {accuracy}")
        print("="*50)

    # BEST MODEL
    best_model_name = max(scores)
    best_pipeline = trained_pipelines[best_model_name]

    print(f"\n BEST MODEL: {best_model_name} ({scores[best_model_name]})")

    return best_pipeline, le, X_test, y_test

In [20]:
#=============================================
#            model evalution
#=============================================

def model_evaluation(pipeline, X_test, y_test,y_pred):

    # predict
    y_pred = pipeline.predict(X_test)

    # metrics
    acc = accuracy_score(y_test,y_pred)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

    return acc 


In [21]:
import pickle

def save_model(model, label_encoder):

    # Save model
    with open("best_model.pkl", "wb") as f:
        pickle.dump(model, f)

    # Save label encoder
    with open("label_encoder.pkl", "wb") as f:
        pickle.dump(label_encoder, f)

    print("\nModel & Encoder Saved Successfully ✅")


In [22]:
def main():

    # 1. Load Data
    df = data_ingestion()

    # 2. Train Model
    model, label_encoder, X_test, y_test = model_building(df)

    # 3. Evaluate Model
    model_evaluation(model, X_test, y_test, label_encoder)

    # 4. Save Model
    save_model(model, label_encoder)


if __name__ == "__main__":
    main()


[[ 97  27]
 [ 19 109]]
RandomForest Results

RandomForest Accuracy: 0.8174603174603174
[[ 95  29]
 [ 10 118]]
GradientBoosting Results

GradientBoosting Accuracy: 0.8452380952380952
[[ 95  29]
 [ 20 108]]
XGBoost Results

XGBoost Accuracy: 0.8055555555555556

 BEST MODEL: XGBoost (0.8055555555555556)
Accuracy: 0.8055555555555556
Confusion Matrix:
 [[ 95  29]
 [ 20 108]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.77      0.79       124
           1       0.79      0.84      0.82       128

    accuracy                           0.81       252
   macro avg       0.81      0.80      0.81       252
weighted avg       0.81      0.81      0.81       252


Model & Encoder Saved Successfully ✅
